spring:
  application:
    name: catfacts
  datasource:
    url: jdbc:postgresql://localhost:5432/cat?currentSchema=cat
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect